version: "3.8"
services:
  mysql:
    container_name: mysql-ethFruitShop
    image: "mysql"
    restart: always
    env_file:
      - ./mysql.env
    ports:
      - 3306:3306
    networks:
      - fruitShop
  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - mysql
    networks:
      - fruitShop
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - fruitShop
networks:
  fruitShop:
