version: "3.8"
services:
  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    networks:
      - fruitShop
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - fruitShop
networks:
  fruitShop:
